### ISSUE TITLE
Error in dropdown navigation

### ISSUE THREAD

**Issue by IgiMar** [getgrav/grav-theme-quark#163]
Concurring circumstances:
a) a page has several sortable pages under itself: on the navigation menu a scrolldown submenu will be needed to select the sub-pages.
b) fixed-header is disabled
The mouse, hovering over the navigation item related to the parent page, triggers the dropdown menu to scroll down. As long as the mouse moves BELOW the Navigation header the dropdown menu closes so that becomes impossible to select any lower items.

**Comment by freerk55** [comment]
Is this solved in the meantime?
Ik see this problem only in Firefox.
In Google chrome it works fine.
What now? any ideas?

**Comment by jensguballa** [comment]
I can confirm this problem. The behaviour only occurs if fixed-header is disabled.
Same here, works in chrome, but does not work in firefox. 
Is any more information required?

**Comment by awrog** [comment]
I can also confirm this problem still exists in grav-theme-quark-2.1.0. The behaviour only occurs if fixed-header is disabled.
